import "moment/locale/es";

export const es: { [key: string]: string } = {
   Error: "Error",
   OK: "OK",
   Cancel: "Cancelar",
   Close: "Cerrar",
   Continue: "Continuar",
   Send: "Enviar",
   "I fixed it": "Ya lo arreglé",
   "Try again": "Reintentar",
   notifications: "notificaciones",
   location: "ubicación",
   "Open location settings": "Abrir opciones de localización",
   "Continue without": "Continuar sin",
   "Continue anyway": "Continuar igualmente",
   "Location is not available":
      "La localización GPS no está disponible, fijate si está desactivada o estás en modo avión",
   "Address is not available":
      "Parte de tu ubicación no se puede leer, recomendamos fijarte que la localización esté activada pero puedes continuar, en teoría debería funcionar bien igualmente",
   "Open app settings": "Ir a la configuración de la app",
   "Exit app": "Salir",
   "Error details": "Detalles del error",
   "The app only works if you accept":
      "La app tiene sentido y funciona si aceptas el permiso que pedimos",
   "Touch on Permissions": 'Toca en "Permisos"',
   "Touch on Camera": 'Toca en "Permisos" y permite "Cámara"',
   "Unexpected error when uploading image": "Error inesperado al subir la imagen",
   "If you want you can help by sending us a screen capture of this error":
      "Nos ayudaría si haces una captura de pantalla de este error y nos lo comunicas",
   "Error when uploading the image": "Error subiendo la imagen",
   "There seems to be a connection problem": "Parece que hay un problema de conexión",
   "Use last one": "Usar anterior",
   January: "Enero",
   February: "Febrero",
   March: "Marzo",
   April: "Abril",
   May: "Mayo",
   June: "Junio",
   July: "Julio",
   August: "Agosto",
   September: "Septiembre",
   October: "Octubre",
   November: "Noviembre",
   December: "Diciembre",
   Woman: "Mujer",
   Man: "Hombre",
   "Transgender Woman": "Mujer trans",
   "Transgender Man": "Hombre trans",
   "Group sex": "Group sex",
   Agender: "Agénero",
   Androgynous: "Androgenx",
   Bigender: "Bigénero",
   Genderfluid: "Género fluido",
   Genderqueer: "Género queer",
   "Gender Nonconforming": "Género disconforme",
   Hijra: "Hijra",
   Intersex: "Intersexual",
   "Non binary": "No binario",
   Other: "Otro",
   Pangender: "Pangénero",
   "Two Spirit": "Género de los dos espíritus",
   "privacy policy": "política de privacidad",
   "community guidelines": "normas comunitarias",
   "terms of use": "términos de uso",
   and: "y",
   "If you continue you agree to our": "Al continuar aceptas nuestras",
   "Report and/or block": "Reportar y/o bloquear",
   Block: "Bloquear",
   "There is no photo of the person": "No hay foto de la persona",
   "The user will be prompted to upload a photo to continue using the app":
      "Se le pedirá que suba una foto para seguir usando la app",
   "Unethical profile": "Perfil no ético",
   "The profile contains unethical elements or violates our community guidelines":
      "Su perfil contiene elementos no éticos o viola nuestras normas comunitarias",
   Comments: "Comentarios",
   optional: "opcional",
   "You declined Facebook permissions that are required":
      "Has rechazado permisos de Facebook que son requeridos",
   "Login with Facebook is not possible": "No se puede iniciar usando Facebook",
   "Maybe you need to login on the Facebook app first":
      "Tal vez primero debes iniciar sesión en la app Facebook",
   "If you make a screenshot of this error and send it to us that would help a lot thanks":
      "Si haces una captura de pantalla de este error y nos la envías, sería de gran ayuda, gracias",
   "Bad Photo": "No hay foto de la persona o es muy mala",
   "Aggressive/Harassment": "Agresividad/Acoso",
   "Sexual Harassment": "Acoso sexual",
   "Spammer/Scammer/Fake": "Spam/Estafador/Fake",
   "Minor (under 18 years old)": "Menor (menos de 18 años)",
   "Offsite behavior: assault / abuse / violence / weapon in a photo":
      "Comportamiento desubicado: agresividad / abuso / violencia / arma en su foto",
   "Error message": "Detalles del error"
};
