import "moment/locale/es";

export const es: { [key: string]: string } = {
   Error: "Error",
   OK: "OK",
   Cancel: "Cancelar",
   Close: "Cerrar",
   "I fixed it": "Ya lo arreglé",
   "Try again": "Reintentar",
   notifications: "notificaciones",
   location: "ubicación",
   "Location is not available":
      "La localización GPS no está disponible, fijate si está desactivada o estás en modo avión",
   "Open app settings": "Ir a la configuración de la app",
   "Exit app": "Salir",
   "Error details": "Detalles del error",
   "The app only works if you accept":
      "La app tiene sentido y funciona si aceptas el permiso que pedimos",
   "Touch on Permissions": 'Toca en "Permisos"',
   "Touch on Camera": 'Toca en "Permisos" y permite "Cámara"',
   "Unexpected error when uploading image": "Error inesperado al subir la imagen",
   "If you want you can help by sending us a screen capture of this error":
      "Nos ayudaría si haces una captura de pantalla de este error y nos lo comunicas",
   "Error when uploading the image": "Error subiendo la imagen",
   "There seems to be a connection problem": "Parece que hay un problema de conexión",
   "Use last one": "Usar anterior",
   January: "Enero",
   February: "Febrero",
   March: "Marzo",
   April: "Abril",
   May: "Mayo",
   June: "Junio",
   July: "Julio",
   August: "Agosto",
   September: "Septiembre",
   October: "Octubre",
   November: "Noviembre",
   December: "Diciembre",
   Woman: "Mujer",
   Man: "Hombre",
   "Transgender Woman": "Mujer transexual",
   "Transgender Man": "Hombre transexual",
   "Group sex": "Group sex",
   Agender: "Agénero",
   Androgynous: "Androgenx",
   Bigender: "Bigénero",
   Genderfluid: "Género fluido",
   Genderqueer: "Género queer",
   "Gender Nonconforming": "Género disconforme",
   Hijra: "Hijra",
   Intersex: "Intersexual",
   "Non binary": "No binario",
   Other: "Otro",
   Pangender: "Pangénero",
   "Two Spirit": "Género de los dos espíritus"
};
