export const en: { [key: string]: string } = {
   Error: "Error",
   OK: "OK",
   Cancel: "Cancel",
   Close: "Close",
   Continue: "Continue",
   Send: "Send",
   "I fixed it": "I fixed it",
   "Try again": "Try again",
   notifications: "notifications",
   location: "location",
   "Open location settings": "Open location settings",
   "Continue without": "Continue without",
   "Continue anyway": "Continue anyway",
   "Location is not available":
      "GPS location is not available, check if it's disabled or Airplane mode is enabled",
   "Address is not available":
      "Part of your location cannot be read, we recommend to check if you have location disabled but you can continue anyway, probably the app still works fine",
   "Open app settings": "Open app settings",
   "Exit app": "Exit app",
   "Error details": "Error details",
   "The app only works if you accept":
      "The app works and makes sense if you accept the permission that we require",
   "Touch on Permissions": 'Touch on "permissions"',
   "Touch on Camera": 'Touch on "Permissions" then allow "Camera"',
   "Unexpected error when uploading image": "Unexpected error when uploading image",
   "If you want you can help by sending us a screen capture of this error":
      "If you want you can help by sending us a screen capture of this error",
   "Error when uploading the image": "Error when uploading the image",
   "There seems to be a connection problem": "There seems to be a connection problem",
   "Use last one": "Use last one",
   January: "January",
   February: "February",
   March: "March",
   April: "April",
   May: "May",
   June: "June",
   July: "July",
   August: "August",
   September: "September",
   October: "October",
   November: "November",
   December: "December",
   Woman: "Woman",
   Man: "Man",
   "Transgender Woman": "Trans Woman",
   "Transgender Man": "Trans Man",
   Agender: "Agender",
   Androgynous: "Androgynous",
   Bigender: "Bigender",
   Genderfluid: "Genderfluid",
   Genderqueer: "Genderqueer",
   "Gender Nonconforming": "Gender Nonconforming",
   Hijra: "Hijra",
   Intersex: "Intersex",
   "Non binary": "Non binary",
   Other: "Other",
   Pangender: "Pangender",
   "Two Spirit": "Two Spirit",
   "privacy policy": "privacy policy",
   "community guidelines": "community guidelines",
   "terms of use": "terms of use",
   and: "and",
   "If you continue you agree to our": "If you continue you agree to our",
   "Report and/or block": "Report and/or block",
   Block: "Block",
   "There is no photo of the person": "There is no photo of the person",
   "The user will be prompted to upload a photo to continue using the app":
      "The user will be prompted to upload a photo to continue using the app",
   "Unethical profile": "Unethical profile",
   "The profile contains unethical elements or violates our community guidelines":
      "The profile contains unethical elements or violates our community guidelines",
   Comments: "Comments",
   optional: "optional",
   "You declined Facebook permissions that are required":
      "You declined Facebook permissions that are required",
   "Login with Facebook is not possible": "Login with Facebook is not possible",
   "Maybe you need to login on the Facebook app first":
      "Maybe you need to login on the Facebook app first",
   "If you make a screenshot of this error and send it to us that would help a lot thanks":
      "If you make a screenshot of this error and send it to us that would help a lot thanks",
   "Bad Photo": "Bad Photo",
   "Aggressive/Harassment": "Aggressive/Harassment",
   "Sexual Harassment": "Sexual Harassment",
   "Spammer/Scammer/Fake": "Spammer/Scammer/Fake",
   "Minor (under 18 years old)": "Minor (under 18 years old)",
   "Offsite behavior: assault / abuse / violence / weapon in a photo":
      "Offsite behavior: assault / abuse / violence / weapon in a photo",
   "Error message": "Error message"
};
