export const en: { [key: string]: string } = {
   Error: "Error",
   OK: "OK",
   Cancel: "Cancel",
   Close: "Close",
   Continue: "Continue",
   "I fixed it": "I fixed it",
   "Try again": "Try again",
   notifications: "notifications",
   location: "location",
   "Open location settings": "Open location settings",
   "Continue without": "Continue without",
   "Continue anyway": "Continue anyway",
   "Location is not available":
      "GPS location is not available, check if it's disabled or Airplane mode is enabled",
   "Address is not available":
      "Part of your location cannot be read, we recommend to check if you have location disabled but you can continue anyway, probably the app still works fine",
   "Open app settings": "Open app settings",
   "Exit app": "Exit app",
   "Error details": "Error details",
   "The app only works if you accept":
      "The app works and makes sense if you accept the permission that we require",
   "Touch on Permissions": 'Touch on "permissions"',
   "Touch on Camera": 'Touch on "Permissions" then allow "Camera"',
   "Unexpected error when uploading image": "Unexpected error when uploading image",
   "If you want you can help by sending us a screen capture of this error":
      "If you want you can help by sending us a screen capture of this error",
   "Error when uploading the image": "Error when uploading the image",
   "There seems to be a connection problem": "There seems to be a connection problem",
   "Use last one": "Use last one",
   January: "January",
   February: "February",
   March: "March",
   April: "April",
   May: "May",
   June: "June",
   July: "July",
   August: "August",
   September: "September",
   October: "October",
   November: "November",
   December: "December",
   Woman: "Woman",
   Man: "Man",
   "Transgender Woman": "Transgender Woman",
   "Transgender Man": "Transgender Man",
   Agender: "Agender",
   Androgynous: "Androgynous",
   Bigender: "Bigender",
   Genderfluid: "Genderfluid",
   Genderqueer: "Genderqueer",
   "Gender Nonconforming": "Gender Nonconforming",
   Hijra: "Hijra",
   Intersex: "Intersex",
   "Non binary": "Non binary",
   Other: "Other",
   Pangender: "Pangender",
   "Two Spirit": "Two Spirit"
};
